# https://taskfile.dev

version: '3'

vars:
  GREETING: "Mac Tools Taskfile"

includes:
  go: go.yml
  minify: minify.yml
  install: install.yml

tasks:
  default:
    cmds:
      - echo {{.GREETING}}
      - task -l 
    silent: true
